cmake_minimum_required(VERSION 3.21)
project(d1x-redux VERSION 1.1)

option(OPENGL "Build with OpenGL support [default: ON]" ON)
option(SDLMIXER "Build with SDL_Mixer support for sound and music (includes external music support) [default: ON]" ON)
option(ASM "Build with ASSEMBLER code (only with OpenGL OFF, requires NASM and x86) [default: OFF]" OFF)
option(EDITOR "Include editor into build (experimental) [default: OFF]" OFF)
option(IPV6 "Enable IPv6 compability [default: OFF]" OFF)
option(UDP "Enable UDP support [default: ON]" ON)
option(TRACKER "Enable Tracker support (requires UDP) [default: ON]" ON)
option(PNG "Build with PNG support for screenshots and textures [default: ON]" ON)
option(OPENGLMERGE "Use an OpenGL shader for texmerge [default: ON]" ON)
option(DXX_USE_BUNDLED_DEPS "Build dependencies from the vendored thirdparty tree" ON)
option(SDL2 "Use SDL2 library [default: OFF]" OFF)

if(SDL2)
    message(FATAL_ERROR "SDL2 application headers are not supported; use the SDL 1.2 API")
endif()

set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} -DRELEASE")
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -DRELEASE")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} -DRELEASE")

if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-address-of-packed-member -Wno-deprecated-declarations")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-format-truncation -Wno-format-overflow")
endif()

if(DXX_USE_BUNDLED_DEPS)
    add_subdirectory(thirdparty EXCLUDE_FROM_ALL)
    set(DXX_SDL_TARGET thirdparty::sdl)
    set(DXX_PHYSFS_TARGET thirdparty::physfs)
    add_library(dxx_game_deps INTERFACE)
    target_link_libraries(dxx_game_deps INTERFACE
        ${DXX_SDL_TARGET}
        ${DXX_PHYSFS_TARGET}
        )
    if(OPENGL)
        set(DXX_GLEW_TARGET thirdparty::glew)
        target_link_libraries(dxx_game_deps INTERFACE ${DXX_GLEW_TARGET})
    endif()
    if(PNG)
        set(DXX_PNG_TARGET thirdparty::png)
        target_link_libraries(dxx_game_deps INTERFACE ${DXX_PNG_TARGET})
    endif()
    if(SDLMIXER)
        set(DXX_SDL_MIXER_TARGET thirdparty::sdl_mixer)
        target_link_libraries(dxx_game_deps INTERFACE ${DXX_SDL_MIXER_TARGET})
    endif()
else()
    find_package(PhysFS REQUIRED)
    include_directories(${PHYSFS_INCLUDE_DIR})
    link_libraries(${PHYSFS_LIBRARY})
endif()

include_directories(arch/include include main)

add_definitions(/DNETWORK)
if(OPENGL)
    add_definitions(/DOGL)
elseif(ASM)
    if(WIN32)
        enable_language(ASM_MASM)
        set(ASM_DIALECT "MASM")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        enable_language(ASM_NASM)
        set(ASM_DIALECT "NASM")
    endif()
endif()
if(NOT DXX_USE_BUNDLED_DEPS)
        find_package(SDL 1.2 REQUIRED)
        link_libraries(${SDL_LIBRARY})
        include_directories(${SDL_INCLUDE_DIR})
endif()
if(SDLMIXER AND NOT DXX_USE_BUNDLED_DEPS)
    add_definitions(/DUSE_SDLMIXER)
    if (APPLE)
        include(FetchContent)
        FetchContent_Declare(
            SDL_mixer-1.2-cmake
            GIT_REPOSITORY https://github.com
            GIT_TAG master
        )
        FetchContent_MakeAvailable(SDL_mixer-1.2-cmake)
        link_libraries(SDL_mixer-1.2-cmake::SDL_mixer-1.2-cmake)
    else()
        find_package(SDL_mixer REQUIRED)
        link_libraries(${SDL_MIXER_LIBRARY})
    endif()
endif()
if(SDLMIXER AND DXX_USE_BUNDLED_DEPS)
    add_definitions(/DUSE_SDLMIXER)
endif()
if(EDITOR)
    add_definitions(/DEDITOR)
endif()
if(IPV6)
    add_definitions(/DIPv6)
endif()
if(UDP)
    add_definitions(/DUSE_UDP)
    if(TRACKER)
        add_definitions(/DUSE_TRACKER)
    endif()
endif()
if(PNG)
    add_definitions(/DHAVE_LIBPNG)
endif()
if(OPENGLMERGE)
    add_definitions(/DOGL_MERGE)
endif()

if(WIN32)
    add_definitions(/DWINDOWS /DHAVE_STRUCT_TIMEVAL /DWINDOWS_IGNORE_PACKING_MISMATCH)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        add_compile_options(-gcodeview -fms-extensions -fseh-exceptions)
        add_link_options(-fuse-ld=lld -Wl,--pdb=)
    endif()
elseif(APPLE)
    add_definitions(/DHAVE_STRUCT_TIMESPEC /DHAVE_STRUCT_TIMEVAL /D__unix__)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_definitions(/D__LINUX__ /DHAVE_STRUCT_TIMESPEC /DHAVE_STRUCT_TIMEVAL)
endif()

if(NOT WIN32)
    add_compile_definitions(SHAREPATH="/usr/share/games/d1x-redux")
endif()

add_subdirectory(2d)
add_subdirectory(3d)
add_subdirectory(arch/sdl)
add_subdirectory(iff)
add_subdirectory(main)
add_subdirectory(maths)
add_subdirectory(mem)
add_subdirectory(misc)
add_subdirectory(texmap)

if(DXX_USE_BUNDLED_DEPS)
    if(SDLMIXER)
        target_link_libraries(arch_sdl PUBLIC ${DXX_SDL_MIXER_TARGET})
        target_link_libraries(d1x-redux PRIVATE ${DXX_SDL_MIXER_TARGET})
    endif()
endif()

add_dependencies(d1x-redux 2d 3d arch_sdl iff maths mem misc texmap)

if(WIN32)
    add_subdirectory(arch/win32)
    add_dependencies(d1x-redux arch_win32)

    # Build as a GUI subsystem application so that Windows never creates a
    # console window for the game. main() still receives argc/argv through the
    # libmingw32 WinMain wrapper, and inferno.c allocates a console on demand
    # when -debug or -verbose is given, so the game window is the only window
    # on screen during a normal launch.
    set_target_properties(d1x-redux PROPERTIES WIN32_EXECUTABLE TRUE)
endif()

if(APPLE)
    add_subdirectory(arch/cocoa)
    add_dependencies(d1x-redux arch_cocoa)
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_subdirectory(arch/x11)
    add_dependencies(d1x-redux arch_x11)
endif()

if(OPENGL)
    add_subdirectory(arch/ogl)
    add_subdirectory(xmodel)
    if(DXX_USE_BUNDLED_DEPS)
        target_link_libraries(arch_ogl PUBLIC ${DXX_SDL_TARGET})
    endif()
    add_dependencies(d1x-redux arch_ogl xmodel)
endif()

if(EDITOR)
    add_subdirectory(editor)
    add_subdirectory(ui)
    add_dependencies(d1x-redux editor ui)
endif()

if(DXX_USE_BUNDLED_DEPS)
    foreach(_dxx_game_target IN ITEMS
            2d 3d arch_sdl arch_win32 arch_x11 arch_cocoa arch_ogl
            editor iff main d1x-redux maths mem misc texmap ui xmodel)
        if(TARGET "${_dxx_game_target}")
            target_link_libraries("${_dxx_game_target}" PRIVATE dxx_game_deps)
        endif()
    endforeach()
endif()
